### ISSUE TITLE
.svf.cfg files

### ISSUE THREAD

**Issue by Simon-Str** [shamedgh/temporal-specialization-artifacts#12]
I am using your project for university. How are the .svf.cfg files generated? In the app.to.properties.json it is just mentioned.

I am thankful for any help!

**Comment by shamedgh** [comment]
You can follow the steps in page: https://github.com/shamedgh/temporal-specialization/blob/master/INSTALL.md
Section 3 describes how to generate the callgraphs.

**Comment by Simon-Str** [comment]
I did everything as in your INSTALL.md. I try to compile and analyze "ls". I just generate a "ls.svf.type.cfg" file and also the search in this repo shows only 2 results:

- in /callgraphs there is a provided file called httpd.apr.svf.cfg
- in app.to.properties.json as an entry

I generated the $BINARY.svf.type.cfg
I could not find how to create e.g. httpd.apr.svf.cfg or in my case $BINARY.svf.cfg  (tried it with ls).

I added an entry to app.to.properties.json:
```
 "apps": [
        {
             "ls":
                {
                    "enable": "true",
                    "cfg": {
                            "direct" : "ls.svf.conditional.direct.calls.cfg",
                            "svf" : "ls.svf.cfg",
                            "svftype" : "ls.svf.type.cfg",
                            "svftypefp" : "ls.svf.new.type.fp.wglobal.cfg"
                           },
                    "master": "main",
                    "worker": "child_main",
                    "bininput": "ls/",
                    "output": "ls.syscall.out"
                },
``` 

This lead to the error "File doesn't exist: /home/vagrant/temporal-specialization/callgraphs/ls.svf.cfg" .
I also copied the previously compiled binary to /binaries/ls/ and the bitcode to its place.

Everything else works, I just don't understand how to create or where to get the $BINARY.svf.cfg from.

Thanks in advance

**Comment by shamedgh** [comment]
Sorry, I misunderstood your question.

The $BINARY.svf.cfg is the baseline callgraph which should be generated using the vanilla SVF.
We used SVF v1.7 and made modifications to apply type-based pruning.
So you have to download and compile [SVF v1.7](https://github.com/SVF-tools/SVF/archive/refs/tags/SVF-1.7.tar.gz) and compile and use it to generate the program's callgraph. 
Command to use after you have the vanilla SVF version: `wpa -ander -dump-callgraph [path_to_bitcode]`
Then use the python script: [convertSvfCfgToHumanReadable.py](https://github.com/shamedgh/temporal-specialization/blob/master/convertSvfCfgToHumanReadable.py) to convert it to the format used by our scripts.

Thanks!

**Comment by Simon-Str** [comment]
Sorry, to need assistance again.
In SVF v1.7 (in the repo and also in the provided link) there is no spa.cpp and therefore no spa binary and therefore I cannot create:

- $BINARY.svf.conditional.direct.calls.cfg
- $BINARY.svf.function.pointer.allocations.wglobal.cfg

using the graphCleaner.py is therefore also not possible and also not createSyscallStats.py.
I tried adding just the line $BINARY.svf.type.cfg to app.to.properties.json but that gave me an error.

**Comment by shamedgh** [comment]
We added the SPA analysis to SVF due to our own need. Therefore it's not available in the SVF repository available online.
However, the code is in the SVF folder provided in this repository:
https://github.com/shamedgh/temporal-specialization/blob/master/SVF/tools/WPA/spa.cpp
It should be built when compiling the SVF in this repository.

In general, you should only use the original SVF repository to build the baseline callgraph ($BINARY.svf.cfg). For the rest, you should use the SVF provided in this repository.
